export const SIGNUP_REQUEST = "USERS_REGISTER_REQUEST";
export const SIGNUP_SUCCESS = "USERS_REGISTER_SUCCESS";
export const SIGNUP_FAILURE = "USERS_REGISTER_FAILURE";

export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = "USERS_LOGIN_SUCCESS";
export const LOGIN_FAILURE = "USERS_LOGIN_FAILURE";

export const LOGOUT_REQUEST = 'USERS_LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'USERS_LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'USERS_LOGOUT_FAILURE';

export const CURRENTUSER_REQUEST = 'USERS_CURRENT_REQUEST';
export const CURRENTUSER_SUCCESS = 'USERS_CURRENT_SUCCESS';
export const CURRENTUSER_FAILURE = 'USERS_CURRENT_FAILURE';